// Generated by CoffeeScript 1.7.1
var LocalStrategy, User, app, bcrypt, bind, codes, db, defaultAppList, earliestUndefined, enter, express, featured_apps, flash, fs, getNewSessionID, http, httpServer, https, io, keyOptions, killSession, login, makeId, makeKey, makeToken, mongoose, nodemailer, normalHome, options, partials, passport, register, salt, secrets, sessions, socket, sslHome, transporter, vOS_App, vOS_Schema, verifySignedIn;

socket = require('socket.io');

fs = require('fs');

express = require('express');

login = require('connect-ensure-login');

passport = require('passport');

partials = require('express-partials');

mongoose = require('mongoose');

LocalStrategy = require('passport-local').Strategy;

bcrypt = require('bcrypt');

secrets = require('./secrets.json');

http = require('http');

https = require('https');

flash = require('connect-flash');

nodemailer = require('nodemailer');

transporter = nodemailer.createTransport({
  service: 'Gmail',
  auth: {
    user: 'ovsak.gavin',
    pass: 'hvagnzflmrssbvkn'
  }
});

salt = bcrypt.genSaltSync(10);

normalHome = 'http://vos.jit.su';

sslHome = 'https://vos.jit.su';

mongoose.connect(secrets.mongoURL);

vOS_Schema = mongoose.Schema({
  name: String,
  description: String,
  url: String,
  owner: String,
  code: String
});

vOS_App = mongoose.model('vOS_App', vOS_Schema);

User = mongoose.model('User', {
  name: String,
  email: String,
  password: String,
  token: String,
  sessionID: String,
  recent: Array,
  friends: Array
});

db = mongoose.connection;

db.on('error', console.error.bind(console, 'connection error:'));

db.once('open', function() {

  /*
  User.remove({email: 'e'}, ->
    console.log('Wiped People')
  )
   */
  return vOS_App.find({}, function() {
    return console.log(arguments);
  });
});

defaultAppList = ['5408e589fe909b00008fca2d', '5408e56bfe909b00008fca2c'];

featured_apps = ['5408e589fe909b00008fca2d', '5408e56bfe909b00008fca2c', '543cc3cb432f59e6b37f3c1d'];

passport.serializeUser(function(user, done) {
  return done(null, user._id);
});

passport.deserializeUser(function(obj, done) {
  return User.findOne({
    _id: obj
  }, function(err, person) {
    return done(err, person);
  });
});

passport.use(new LocalStrategy({
  usernameField: 'email',
  passwordField: 'password'
}, function(email, password, done) {
  return User.find({
    email: email
  }, function(err, people) {
    var once, person, _i, _len;
    console.log(people);
    if (err != null) {
      done(err);
    }
    once = true;
    for (_i = 0, _len = people.length; _i < _len; _i++) {
      person = people[_i];
      console.log([arguments, person]);
      if (bcrypt.compareSync(password, person.password) && once) {
        done(null, people[0]);
        once = false;
      }
    }
    if (once) {
      return done(null);
    }
  });
}));

app = express();

app.set('views', __dirname + '/views');

app.set('view engine', 'ejs');

app.use(partials());

app.use(express.cookieParser());

app.use(express.bodyParser());

app.use(express.errorHandler({
  dumpExceptions: true,
  showStack: true
}));

app.use(express.session({
  secret: 'virtual OS secret'
}));

app.use(passport.initialize());

app.use(passport.session());

app.use(flash());

app.use(app.router);

app.use('/js', express["static"](__dirname + '/js'));

app.use('/Browserify', express["static"](__dirname + '/Browserify'));

app.use('/css', express["static"](__dirname + '/css'));

app.use('/fonts', express["static"](__dirname + '/fonts'));

app.use('/static', express["static"](__dirname + '/public'));

app.get('/latestAPK', function(req, res) {
  var file;
  file = __dirname + '/public/vOS_Controller.apk';
  return res.download(file);
});

verifySignedIn = function(req, res, next) {
  if (req.user != null) {
    return next();
  }
  req.flash('error', 'Please Sign In First');
  return res.redirect(normalHome + '?from=' + encodeURIComponent(req.url));
};

app.post('/signin', passport.authenticate('local', {
  failureRedirect: '/fail'
}), function(req, res) {
  console.log(req.query);
  if ((req.query.from != null) && req.query.from !== '') {
    return res.redirect(decodeURIComponent(req.query.from));
  } else {
    return res.redirect(normalHome);
  }
});

app.get('/fail', function(req, res) {
  req.flash('error', "Oops, I cannot let you in!");
  return res.redirect(normalHome);
});

register = function(name, email, password, succeed, fail) {
  return User.find({
    email: email
  }, function(err, people) {
    var user;
    if (err != null) {
      console.log(err);
    }
    if (people.length > 0) {
      if (bcrypt.compareSync(password, people[0].password)) {
        user = people[0];
      } else {
        return fail();
      }
    }
    if (!user && name && password) {
      user = new User({
        name: name,
        email: email,
        password: bcrypt.hashSync(password, salt),
        recent: defaultAppList
      });
      user.save(function(err, user) {
        if (err != null) {
          console.log(err);
        }
        return console.log(user);
      });
    }
    if (user != null) {
      return succeed(user);
    } else {
      return fail();
    }
  });
};

makeToken = function(done) {
  var token;
  token = '' + Math.floor(Math.random() * Math.pow(10, 10));
  return User.findOne({
    token: token
  }, function(err, user) {
    if (err != null) {
      console.log(err);
    }
    if (user != null) {
      return makeToken(done);
    } else {
      return done(token);
    }
  });
};

app.post('/registerAndSignIn', function(req, res) {
  return register(req.body.name, req.body.email, req.body.password, function(user) {
    return req.login(user, function(err) {
      if (err != null) {
        console.log(err);
      }
      return res.redirect(normalHome);
    });
  }, function() {
    console.log('Email already exists with a different password or there are missing fields');
    return res.redirect(normalHome);
  });
});

app.post('/registerForToken', function(req, res) {
  return register(req.body.name, req.body.email, req.body.password, function(user) {
    return makeToken(function(token) {
      user.token = token;
      user.save(function(err, user) {
        if (err != null) {
          return console.log(err);
        }
      });
      return res.json(user);
    });
  }, function() {
    console.log('Email already exists with a different password or there are missing fields');
    return res.json('Email already exists with a different password or there are missing fields');
  });
});

app.get('/userFromToken', function(req, res) {
  if (req.query.token != null) {
    return User.findOne({
      token: req.query.token
    }, function(err, user) {
      var publicUser;
      if (err != null) {
        console.log(err);
      }
      if (user != null) {
        publicUser = {
          name: user.name,
          recent: user.recent,
          id: user._id
        };
        return res.json(publicUser);
      } else {
        console.log(user);
        console.log(req.query.token);
        return res.json();
      }
    });
  }
});

app.post('/user', [
  verifySignedIn, function(req, res) {
    var publicUser;
    if (req.user != null) {
      if (req.body.name != null) {
        req.user.name = req.body.name;
      }
      if (req.body.password != null) {
        req.user.password = bcrypt.hashSync(req.body.password, salt);
      }
      req.user.save(function(err, user) {
        if (err != null) {
          return console.log(err);
        }
      });
      publicUser = {
        name: req.user.name,
        recent: req.user.recent,
        id: req.user._id
      };
      return res.json(publicUser);
    } else {
      console.log(req.user);
      console.log(req.query.token);
      return res.json();
    }
  }
]);

makeId = function() {
  var i, possible, text, _i;
  text = "";
  possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for (i = _i = 0; _i <= 8; i = ++_i) {
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  }
  return text;
};

app.post('/forgot', function(req, res) {
  if (req.body.email != null) {
    return User.findOne({
      email: req.body.email
    }, function(err, user) {
      var mailOptions, publicUser, tempPass;
      if (err != null) {
        console.log(err);
      }
      if (user != null) {
        tempPass = makeId();
        mailOptions = {
          from: 'Gavin from vOS <ovsak.gavin@gmail.com>',
          to: req.body.email,
          subject: 'Password Reset',
          text: 'Your new password for http://vos.jit.su is: ' + tempPass + ' . Please change it to something more memorable!',
          html: 'Your new password for <a href="http://vos.jit.su">http://vos.jit.su</a> is: <b>' + tempPass + '</b> . Please change it to something more memorable!'
        };
        transporter.sendMail(mailOptions, function(error, info) {
          if (error != null) {
            return console.log(error);
          } else {
            return console.log('Message sent: ' + info.response);
          }
        });
        user.password = bcrypt.hashSync(tempPass, salt);
        user.save(function(err, user) {
          if (err != null) {
            return console.log(err);
          }
        });
        publicUser = {
          name: user.name,
          id: user._id
        };
        return res.json(publicUser);
      } else {
        return res.json('No account found');
      }
    });
  } else {
    return res.json('No account found');
  }
});

app["delete"]('/user', [
  verifySignedIn, function(req, res) {
    var publicUser;
    if (req.user != null) {
      publicUser = {
        name: req.user.name,
        recent: req.user.recent,
        id: req.user._id
      };
      res.json(publicUser);
      req.user.remove();
      req.logout();
      return res.redirect('/');
    } else {
      console.log(req.user);
      console.log(req.query.token);
      return res.json();
    }
  }
]);

app.get('/signout', function(req, res) {
  req.logout();
  return res.redirect(normalHome);
});

app.post('/newAppUsed', function(req, res) {
  if (req.query.token != null) {
    return User.findOne({
      token: req.query.token
    }, function(err, user) {
      var index;
      if (err != null) {
        console.log(err);
      }
      if ((user != null) && (req.body.appID != null)) {
        index = user.recent.indexOf(req.body.appID);
        if (index >= 0) {
          user.recent.splice(index, 1);
        }
        user.recent.push(req.body.appID);
        user.save(function(err, user) {
          if (err != null) {
            console.log(err);
          }
          return console.log('Successful App Update');
        });
        return res.json(user);
      } else {
        return res.json(req.body);
      }
    });
  } else {
    return res.json(req.body);
  }
});

app.post('/removeAppMRU', function(req, res) {
  if (req.query.token != null) {
    return User.findOne({
      token: req.query.token
    }, function(err, user) {
      var index;
      if (err != null) {
        console.log(err);
      }
      if ((user != null) && (req.body.appID != null)) {
        index = user.recent.indexOf(req.body.appID);
        if (index >= 0) {
          user.recent.splice(index, 1);
        }
        user.save(function(err, user) {
          if (err != null) {
            console.log(err);
          }
          return console.log('Successful App Update');
        });
        return res.json(user);
      } else {
        return res.json(req.body);
      }
    });
  } else {
    return res.json(req.body);
  }
});


/*
app.post('/recentApps', (req, res) ->
  if req.query.token?
    User.findOne token: req.query.token, (err, user) ->
      console.log err if err?
      if user? and req.body.recent.constructor is Array
        user.recent = req.body.recent
        user.save((err, user) ->
          console.log err if err?
          console.log 'Successful App Update'
        )
        res.json(user)
      else
        res.json(req.body)
  else 
    res.json(req.body)
)
 */


/*
app.get('/appList', [
  verifySignedIn,
  (req, res) ->
    vOS_App.find {}, (err, apps) ->
      console.log err if err?
 *      console.log(apps)
      res.json apps
])
 */

app.get('/hosted', function(req, res) {
  if (req.query.id != null) {
    return vOS_App.findOne({
      _id: req.query.id
    }, function(err, app) {
      if (err != null) {
        console.log(err);
      }
      if ((app != null) && (app.code != null)) {
        res.writeHead(200, {
          'Content-Type': 'application/javascript'
        });
        res.write(app.code);
        return res.end();
      } else {
        return res.json();
      }
    });
  } else {
    return res.json();
  }
});

app.post('/dashboard/update', [
  verifySignedIn, function(req, res) {
    var newApp, options, update;
    update = req.body;
    console.log(update);
    if (update.id) {
      return vOS_App.findOne({
        _id: update.id
      }, function(err, app) {
        if (err != null) {
          console.log(err);
        }
        if (app != null) {
          if (update.name != null) {
            app.name = update.name;
          }
          if (update.description != null) {
            app.description = update.description;
          }
          if (update.url != null) {
            app.url = update.url;
          }
          if (update.code != null) {
            app.code = update.code;
          }
          res.json(app);
          return app.save(function(err, user) {
            if (err != null) {
              return console.log(err);
            }
          });
        } else {
          return res.json(void 0);
        }
      });
    } else {
      options = {
        name: update.name,
        description: update.description,
        url: update.url,
        owner: req.user._id
      };
      if (update.code != null) {
        options.code = update.code;
      }
      newApp = new vOS_App(options);
      if ((newApp.code != null) && newApp.url === 'upload') {
        newApp.url = 'http://vos.jit.su/hosted?id=' + newApp._id;
      }
      return newApp.save(function(err, user) {
        if (err != null) {
          console.log(err);
        }
        console.log(user);
        res.json(user);
        return console.log('Successful New App');
      });
    }
  }
]);

app.get('/dashboard', [
  verifySignedIn, function(req, res) {
    return vOS_App.find({
      owner: req.user._id
    }, function(err, apps) {
      if (err != null) {
        console.log(err);
      }
      return res.render('dashboard', {
        user: req.user,
        apps: apps
      });
    });
  }
]);

app.get('/appInfo', [
  function(req, res) {
    if (req.query.app_id) {
      return vOS_App.findOne({
        _id: req.query.app_id
      }, function(err, app) {
        if (err != null) {
          console.log(err);
        }
        console.log(app);
        return res.json(app);
      });
    } else {
      return res.json(null);
    }
  }
]);

app.get('/all', function(req, res) {
  return vOS_App.find({}, function(err, apps) {
    return res.render('all', {
      user: req.user,
      allApps: apps
    });
  });
});

app.get('/app', function(req, res) {
  return vOS_App.findOne({
    _id: req.query.app_id
  }, function(err, app) {
    if (err != null) {
      console.log(err);
    }
    return res.render('app', {
      user: req.user,
      app: app
    });
  });
});

app.get('/appSearchJSON', function(req, res) {
  console.log(req.query.query);
  if ((req.query.query != null) && req.query.query !== '') {
    return vOS_App.find({
      $or: [
        {
          description: {
            '$regex': '.*' + req.query.query + '.*',
            $options: 'i'
          }
        }, {
          name: {
            '$regex': '.*' + req.query.query + '.*',
            $options: 'i'
          }
        }
      ]
    }).sort({
      '_id': -1
    }).limit(10).exec(function(err, apps) {
      if (err != null) {
        console.log(err);
      }
      return res.json(apps);
    });
  } else {
    return res.json([]);
  }
});

app.get('/appSearch', function(req, res) {
  return vOS_App.find({
    $or: [
      {
        description: {
          '$regex': '.*' + req.query.query + '.*',
          $options: 'i'
        }
      }, {
        name: {
          '$regex': '.*' + req.query.query + '.*',
          $options: 'i'
        }
      }
    ]
  }).sort({
    '_id': -1
  }).limit(10).exec(function(err, apps) {
    if (err != null) {
      console.log(err);
    }
    return res.render('appSearch', {
      user: req.user,
      query: req.query.query,
      results: apps
    });
  });

  /*
  vOS_App.find( {_id: req.query}, function(err, app) {
    console.log(app)
    res.render('appSearch', {
      user: undefined,
      home: false,
      app: app
    })
  })
   */
});

app["delete"]('/app', function(req, res) {
  return vOS_App.remove({
    _id: req.query.app_id
  }, function(err, app) {
    return res.json(app);
  });
});

app.get('/', function(req, res) {
  return vOS_App.findOne({
    _id: featured_apps[0]
  }, function(err, app) {
    if (err != null) {
      console.log(err);
    }
    console.log(app);
    return res.render('home', {
      user: req.user,
      featured: featured_apps,
      displayApp: app,
      message: req.flash('error')
    });
  });
});

app.get('/documentation', function(req, res) {
  return res.render('documentation', {
    user: req.user
  });
});

app.get('/about', function(req, res) {
  return res.render('about', {
    user: req.user
  });
});

app.get('/try', function(req, res) {
  return res.render('try', {
    user: req.user
  });
});

app.get('/account', [
  verifySignedIn, function(req, res) {
    return res.render('account', {
      user: req.user
    });
  }
]);

app.get('/forgot', function(req, res) {
  return res.render('forgot', {
    user: req.user
  });
});

app.get('/debug', function(req, res) {
  var recents, render;
  recents = defaultAppList;
  render = function(app) {
    return res.render('vOS', {
      user: {
        debug: true
      },
      layout: false,
      session_id: 'debug',
      recentApps: recents,
      token: 'debug',
      app: app
    });
  };
  if (req.query.app_id) {
    return vOS_App.findOne({
      _id: req.query.app_id
    }, function(err, app) {
      return render(app);
    });
  } else {
    return render(void 0);
  }
});

app.get('/local', function(req, res) {
  return res.render('local', {
    user: req.user
  });
});

enter = function(req, res, viewName) {
  var recents, _ref;
  console.log('entering');
  console.log(req.query.session_id);
  console.log(sessions);
  console.log(sessions[req.query.session_id]);
  if ((req.query.session_id != null) && (((_ref = sessions[req.query.session_id]) != null ? _ref.input : void 0) != null) && (sessions[req.query.session_id].output == null)) {
    recents = defaultAppList;
    return User.findOne({
      token: sessions[req.query.session_id].token
    }, function(err, user) {
      if (user != null) {
        recents = user.recents;
      }
      if ((recents == null) || recents.length === 0) {
        recents = defaultAppList;
      }
      if (req.query.app_id) {
        if ((user != null) && (!user.recents || user.recents.indexOf(req.query.app_id === -1))) {
          if (user.recents == null) {
            user.recents = [];
          }
          user.recents.push(req.query.app_id);
          user.save(function(err, user) {
            if (err != null) {
              console.log(err);
            }
            return console.log('Added New Recent App');
          });
        }
      }
      return vOS_App.findOne({
        _id: req.query.app_id
      }, function(err, app) {
        if (err != null) {
          console.log(err);
        }
        console.log(app);
        return res.render(viewName, {
          layout: false,
          session_id: req.query.session_id,
          token: sessions[req.query.session_id].token,
          user: user,
          app: app
        });
      });
    });
  } else {
    console.log('going back');
    return res.redirect(req.query.from != null ? req.query.from : '/');
  }
};

app.get('/enterLocal', function(req, res) {
  return enter(req, res, 'localvOS');
});

app.get('/enterCardboard', function(req, res) {
  return enter(req, res, 'cardboardvOS');
});

app.get('/cardboard', function(req, res) {
  return res.render('cardboard', {
    layout: false
  });
});

app.get('/pair', function(req, res) {
  return res.render('pair', {
    layout: false
  });
});

app.get('/getUsers', function(req, res) {
  return User.find({}, function(err, people) {
    return res.json(people);
  });
});

app.get('/getApps', function(req, res) {
  return vOS_App.find({}, function(err, apps) {
    return res.json(apps);
  });
});

app.get('/removeUser', function(req, res) {
  return User.remove({
    _id: req.query.id
  }, function(err, people) {
    return res.json(people);
  });
});

app.get('/removeApp', function(req, res) {
  return vOS_App.remove({
    _id: req.query.id
  }, function(err, apps) {
    return res.json(apps);
  });
});

app.get('/enter', function(req, res) {
  return enter(req, res, 'vOS');
});

app.get('/mirror', [
  verifySignedIn, function(req, res) {
    var options;
    options = {
      layout: false,
      session_id: req.query.session_id,
      user: req.user,
      view: req.query.view,
      token: req.user.token
    };

    /*
    if sessions[req.query.session_id]?.token?
      options.token = sessions[req.query.session_id].token
    else
      options.token = null
     */
    return res.render('mirror', options);
  }
]);

options = {
  key: secrets.ssl.key,
  cert: secrets.ssl.cert
};

httpServer = http.createServer(app).listen(8081);

io = socket.listen(httpServer);

io.set('log level', 0);

keyOptions = ['2', '3', '4', '6', '7', '9', 'A', 'C', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];

codes = {

  /*  "AAA": {socket: websiteSocket, name: name}
   */
};

earliestUndefined = 0;

getNewSessionID = function() {
  while (sessions[earliestUndefined]) {
    earliestUndefined++;
  }
  return earliestUndefined;
};

sessions = [];


/*"1234234": {
  userID: 1,
  input: inputSocket,
  output: outputSocket
}
 */

makeKey = function() {
  var key;
  key = '';
  while (key === '' || codes[key]) {
    key = '';
    key += keyOptions[Math.floor(Math.random() * keyOptions.length)];
    key += keyOptions[Math.floor(Math.random() * keyOptions.length)];
    key += keyOptions[Math.floor(Math.random() * keyOptions.length)];
  }
  return key;
};

bind = function(session) {
  session.input.on('start', function(data) {
    session.output.emit('start', data);
    return console.log('emit: start, ' + data);
  });
  session.input.on('move', function(data) {
    session.output.emit('move', data);
    return console.log('emit: move, ' + data);
  });
  session.input.on('end', function(data) {
    session.output.emit('end', data);
    return console.log('emit: end, ' + data);
  });
  session.input.on('size', function(data) {
    session.output.emit('size', data);
    return console.log('emit: size, ' + data);
  });
  session.input.on('value', function(data) {
    return session.output.emit('value', data);
  });
  if (session.passVisuals) {
    session.output.on('visual', function(data) {
      return session.input.emit('visual', data);
    });
  }
  return session.input.emit('response', 'ready');
};

killSession = function(session_id) {
  console.log('killing session ' + session_id);
  if (sessions[session_id]) {
    if (sessions[session_id].input != null) {
      sessions[session_id].input.emit('error', 'output disconnected');
    }
    if (sessions[session_id].output != null) {
      sessions[session_id].output.emit('error', 'input disconnected');
    }
    delete sessions[session_id];
    return earliestUndefined = session_id;
  }
};

io.sockets.on('connection', function(socket) {
  socket.on('ping', function(data) {
    return socket.emit('ping-back', data);
  });
  return socket.on('declare-type', function(data) {
    var key, mirrors, session;
    console.log(data.type);
    if (data.type === 'page') {
      key = makeKey();
      codes[key] = {
        socket: socket,
        name: data.name
      };
      socket.emit('code', {
        code: key,
        name: data.name
      });
      socket.on('disconnect', function() {
        return delete codes[key];
      });
    }
    if (data.type === 'mirror') {
      console.log('got mirror');
      if ((sessions[data.session_id] != null) && (data.view != null) && (data.token != null) && sessions[data.session_id].token === data.token) {
        mirrors = sessions[data.session_id].mirrors;
        if (mirrors[data.view] == null) {
          mirrors[data.view] = [];
        }
        mirrors[data.view].push(socket);
        console.log(['D', mirrors[data.view]]);
        sessions[data.session_id].output.emit('mirror-views', Object.keys(sessions[data.session_id].mirrors));
        socket.on('mirror-data', function(reqData) {
          reqData.view = data.view;
          return sessions[data.session_id].output.emit('mirror-data', reqData);
        });
        socket.on('disconnect', function() {});
      }
    }
    if (data.type === 'output') {
      console.log('got output');
      if ((data.session_id != null) && (sessions[data.session_id] != null) && (sessions[data.session_id].output == null)) {
        session = sessions[data.session_id];
        session.output = socket;
        console.log('binding');
        bind(session);
        session.output.on('disconnect', function() {
          return killSession(data.session_id);
        });
        session.output.on('mirror', function(data) {
          var mirror, _i, _len, _ref, _results;
          console.log('mirror incoming');
          console.log(session.mirrors[data.view]);
          if (session.mirrors[data.view] != null) {
            _ref = session.mirrors[data.view];
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              mirror = _ref[_i];
              console.log('emitted');
              _results.push(mirror.emit('mirror', data));
            }
            return _results;
          }
        });
      } else {
        socket.emit('error', 'incorrect session id');
      }
    }
    if (data.type === 'input') {
      console.log('got input');
      console.log(data);
      return User.findOne({
        token: data.token
      }, function(err, user) {
        if (err != null) {
          console.log(err);
        }
        if (user != null) {
          return socket.on('code', function(raw) {
            var code, newSessionID;
            console.log('got code');
            console.log(raw);
            code = raw.toUpperCase();
            if (codes[code] !== void 0) {
              newSessionID = getNewSessionID();
              user.sessionID = newSessionID;
              user.save(function(err, user) {
                if (err != null) {
                  return console.log(err);
                }
              });
              sessions[newSessionID] = {
                token: data.token,
                userID: user._id,
                input: socket,
                mirrors: {},
                passVisuals: data.passVisuals != null ? data.passVisuals : true
              };
              console.log('New session at ' + newSessionID);
              socket.on('disconnect', function() {
                return killSession(newSessionID);
              });
              socket.on('connection', function(status) {
                if (status === 'cancelled') {
                  return killSession(newSessionID);
                }
              });
              socket.emit('response', 'correct pair code');
              codes[code].socket.emit('session_id', {
                id: newSessionID,
                name: codes[code].name
              });
              return delete codes[code];
            } else {
              return socket.emit('error', 'incorrect pair code');
            }
          });
        } else {
          return socket.emit('error', 'bad token');
        }
      });
    }
  });
});
